### ISSUE TITLE
 FAIL  src/App.test.js

### ISSUE THREAD

**Issue by NaniW** [Montana-Code-School/TKD#11]
FAIL  src/App.test.js
  ● Test suite failed to run

    Cannot find module 'axios' from 'Checkout.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:179:17)
      at Object.<anonymous> (src/components/Checkout.js:2:14)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        4.941s
Ran all test suites.

**Comment by chdwck** [comment]
You just had to npm install.
